import type {
  Business,
  BusinessListResponse,
  Category,
} from "@workspace/api-client-react";

const NOW = "2026-04-06T12:00:00.000Z";

function makeImage(id: number, url: string) {
  return { id, url, isPrimary: true };
}

export const fallbackCategories: Category[] = [
  { id: 1, name: "Restaurantes", icon: "UtensilsCrossed", description: "Comida y bebida", businessCount: 3 },
  { id: 2, name: "Tiendas", icon: "ShoppingBag", description: "Comercio local", businessCount: 2 },
  { id: 3, name: "Servicios", icon: "Wrench", description: "Servicios profesionales", businessCount: 2 },
  { id: 4, name: "Salud", icon: "Heart", description: "Salud y bienestar", businessCount: 2 },
  { id: 5, name: "Educacion", icon: "GraduationCap", description: "Formacion y cursos", businessCount: 1 },
  { id: 6, name: "Entretenimiento", icon: "Music", description: "Planes y eventos", businessCount: 1 },
  { id: 7, name: "Tecnologia", icon: "Laptop", description: "Tecnologia y soporte", businessCount: 1 },
  { id: 8, name: "Belleza", icon: "Sparkles", description: "Belleza y cuidado personal", businessCount: 1 },
  { id: 9, name: "Transporte", icon: "Car", description: "Movilidad y mensajeria", businessCount: 1 },
  { id: 10, name: "Hoteles", icon: "Hotel", description: "Hospedaje", businessCount: 1 },
];

export const fallbackBusinesses: Business[] = [
  {
    id: 1001,
    name: "Cafe del Parque",
    description: "Cafe de especialidad con brunch, panaderia artesanal y un ambiente tranquilo cerca del parque principal.",
    address: "Carrera 5 #9-18, Centro, Cartago",
    phone: "3174408891",
    whatsapp: "573174408891",
    instagram: "@cafedelparquecartago",
    facebook: "CafeDelParqueCartago",
    website: "cafedelparque.co",
    googleMapsUrl: "https://maps.google.com/?q=Cafe+del+Parque+Cartago",
    googleMapsEmbed: null,
    schedule: "Lunes a sabado\n7:00 a. m. - 8:00 p. m.",
    categoryId: 1,
    categoryName: "Restaurantes",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10011, "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.8,
    reviewCount: 126,
    createdAt: NOW,
  },
  {
    id: 1002,
    name: "Pizza Don Marco",
    description: "Pizza artesanal al horno de lena, pastas frescas y servicio a domicilio en varios barrios de Cartago.",
    address: "Avenida 2 Norte #12-60, Cartago",
    phone: "3203114570",
    whatsapp: "573203114570",
    instagram: "@pizzadonmarco",
    facebook: null,
    website: "pizzadonmarco.com",
    googleMapsUrl: "https://maps.google.com/?q=Pizza+Don+Marco+Cartago",
    googleMapsEmbed: null,
    schedule: "Todos los dias\n12:00 m. - 10:00 p. m.",
    categoryId: 1,
    categoryName: "Restaurantes",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10021, "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.7,
    reviewCount: 98,
    createdAt: NOW,
  },
  {
    id: 1003,
    name: "La Terraza Paisa",
    description: "Comida paisa, carnes y platos familiares con una terraza amplia para reuniones y celebraciones.",
    address: "Avenida 4 Norte #15-30, Cartago",
    phone: "3102345670",
    whatsapp: "573102345670",
    instagram: "@laterrazapaisa",
    facebook: "LaTerrazaPaisa",
    website: "laterrazapaisa.com",
    googleMapsUrl: "https://maps.google.com/?q=La+Terraza+Paisa+Cartago",
    googleMapsEmbed: null,
    schedule: "Lunes a domingo\n11:30 a. m. - 9:30 p. m.",
    categoryId: 1,
    categoryName: "Restaurantes",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10031, "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.6,
    reviewCount: 73,
    createdAt: NOW,
  },
  {
    id: 1004,
    name: "Mercado Verde La 14",
    description: "Frutas, verduras, snacks saludables y mercado fresco con domicilios el mismo dia.",
    address: "Calle 14 #4-17, Cartago",
    phone: "3215019820",
    whatsapp: "573215019820",
    instagram: "@mercadoverdelacatorce",
    facebook: null,
    website: null,
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a domingo\n7:00 a. m. - 7:30 p. m.",
    categoryId: 2,
    categoryName: "Tiendas",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10041, "https://images.unsplash.com/photo-1542838132-92c53300491e?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.5,
    reviewCount: 41,
    createdAt: NOW,
  },
  {
    id: 1005,
    name: "Papeleria Prisma",
    description: "Utiles escolares, impresiones, regalos y apoyo rapido para estudiantes, docentes y oficinas.",
    address: "Carrera 4 #10-41, Cartago",
    phone: "3005123478",
    whatsapp: "573005123478",
    instagram: "@papeleriaprisma",
    facebook: null,
    website: null,
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a sabado\n8:00 a. m. - 7:00 p. m.",
    categoryId: 2,
    categoryName: "Tiendas",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10051, "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.4,
    reviewCount: 29,
    createdAt: NOW,
  },
  {
    id: 1006,
    name: "Nube Creativa Studio",
    description: "Branding, fotografia de producto, diseno y manejo de redes para negocios locales.",
    address: "Avenida del Rio #7-60, Oficina 201, Cartago",
    phone: "3207415520",
    whatsapp: "573207415520",
    instagram: "@nubecreativastudio",
    facebook: "NubeCreativaStudio",
    website: "nubecreativa.studio",
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a viernes\n9:00 a. m. - 6:00 p. m.",
    categoryId: 3,
    categoryName: "Servicios",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10061, "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.9,
    reviewCount: 37,
    createdAt: NOW,
  },
  {
    id: 1007,
    name: "Garcia y Asociados",
    description: "Asesoria legal en derecho civil, comercial y laboral para personas y negocios de Cartago.",
    address: "Carrera 7 #12-55, Piso 3, Cartago",
    phone: "3005678903",
    whatsapp: "573005678903",
    instagram: "@garciayasociados",
    facebook: null,
    website: null,
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a viernes\n8:00 a. m. - 5:30 p. m.",
    categoryId: 3,
    categoryName: "Servicios",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10071, "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.7,
    reviewCount: 22,
    createdAt: NOW,
  },
  {
    id: 1008,
    name: "Optica Vision Central",
    description: "Examenes visuales, monturas modernas y entrega agil de lentes formulados.",
    address: "Calle 11 #6-22, Cartago",
    phone: "3159042210",
    whatsapp: "573159042210",
    instagram: "@visioncentralcartago",
    facebook: "VisionCentralCartago",
    website: "visioncentralcartago.com",
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a viernes\n8:00 a. m. - 6:30 p. m.\nSabados 8:00 a. m. - 2:00 p. m.",
    categoryId: 4,
    categoryName: "Salud",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10081, "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.8,
    reviewCount: 54,
    createdAt: NOW,
  },
  {
    id: 1009,
    name: "Fitness Center Cartago",
    description: "Gimnasio con clases guiadas, entrenamiento funcional y planes para todos los niveles.",
    address: "Calle 13 #7-54, Cartago",
    phone: "3182231445",
    whatsapp: "573182231445",
    instagram: "@fitnesscartago",
    facebook: null,
    website: null,
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a viernes\n5:00 a. m. - 9:00 p. m.\nSabados 7:00 a. m. - 2:00 p. m.",
    categoryId: 4,
    categoryName: "Salud",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10091, "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.6,
    reviewCount: 61,
    createdAt: NOW,
  },
  {
    id: 1010,
    name: "Instituto Saber Digital",
    description: "Cursos cortos en herramientas digitales, ofimatica, marketing y habilidades laborales.",
    address: "Carrera 6 #11-72, Cartago",
    phone: "3162209074",
    whatsapp: "573162209074",
    instagram: "@saberdigitalcartago",
    facebook: "InstitutoSaberDigital",
    website: "saberdigital.edu.co",
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a viernes\n8:00 a. m. - 8:00 p. m.",
    categoryId: 5,
    categoryName: "Educacion",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10101, "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.7,
    reviewCount: 33,
    createdAt: NOW,
  },
  {
    id: 1011,
    name: "Casa Coral Eventos",
    description: "Salon para eventos corporativos, familiares y celebraciones con sonido y catering.",
    address: "Via Ansermanuevo km 2, Cartago",
    phone: "3128805521",
    whatsapp: "573128805521",
    instagram: "@casacoraleventos",
    facebook: "CasaCoralEventos",
    website: "casacoral.co",
    googleMapsUrl: "https://maps.google.com/?q=Casa+Coral+Eventos+Cartago",
    googleMapsEmbed: null,
    schedule: "Atencion por reservas\nTodos los dias 9:00 a. m. - 6:00 p. m.",
    categoryId: 6,
    categoryName: "Entretenimiento",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10111, "https://images.unsplash.com/photo-1511578314322-379afb476865?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.8,
    reviewCount: 45,
    createdAt: NOW,
  },
  {
    id: 1012,
    name: "Tech Store Cartago",
    description: "Celulares, laptops, accesorios y soporte tecnico para hogar y empresa.",
    address: "Calle 12 #4-45, Cartago",
    phone: "3001237788",
    whatsapp: "573001237788",
    instagram: "@techstorecartago",
    facebook: null,
    website: null,
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a sabado\n9:00 a. m. - 7:00 p. m.",
    categoryId: 7,
    categoryName: "Tecnologia",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10121, "https://images.unsplash.com/photo-1518770660439-4636190af475?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.5,
    reviewCount: 39,
    createdAt: NOW,
  },
  {
    id: 1013,
    name: "Salon Glamour",
    description: "Cortes, color, manicure y maquillaje para eventos con atencion personalizada.",
    address: "Carrera 4 #11-20, Cartago",
    phone: "3108901236",
    whatsapp: "573108901236",
    instagram: "@salonglamourcartago",
    facebook: null,
    website: null,
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a sabado\n9:00 a. m. - 7:00 p. m.",
    categoryId: 8,
    categoryName: "Belleza",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10131, "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.8,
    reviewCount: 57,
    createdAt: NOW,
  },
  {
    id: 1014,
    name: "Ruta Express Mensajeria",
    description: "Mensajeria urbana y entregas el mismo dia en Cartago y municipios cercanos.",
    address: "Carrera 3 #14-08, Cartago",
    phone: "3008844201",
    whatsapp: "573008844201",
    instagram: "@rutaexpresscartago",
    facebook: null,
    website: null,
    googleMapsUrl: null,
    googleMapsEmbed: null,
    schedule: "Lunes a sabado\n7:30 a. m. - 6:30 p. m.",
    categoryId: 9,
    categoryName: "Transporte",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10141, "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.4,
    reviewCount: 19,
    createdAt: NOW,
  },
  {
    id: 1015,
    name: "Hotel Santa Monica Plaza",
    description: "Alojamiento ejecutivo con parqueadero, desayuno y wifi para viajeros de negocio y turismo.",
    address: "Calle 12 #5-33, Cartago",
    phone: "3116637822",
    whatsapp: "573116637822",
    instagram: "@hotelsantamonicaplaza",
    facebook: null,
    website: "hotelsantamonicaplaza.com",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Santa+Monica+Plaza+Cartago",
    googleMapsEmbed: null,
    schedule: "Recepcion 24 horas",
    categoryId: 10,
    categoryName: "Hoteles",
    ownerId: 1,
    ownerName: "Equipo Directorio",
    status: "approved",
    images: [makeImage(10151, "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=900&auto=format&fit=crop&q=80")],
    averageRating: 4.7,
    reviewCount: 48,
    createdAt: NOW,
  },
];

function normalizeTerm(value?: string | null) {
  return (value ?? "")
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .trim();
}

export function getFallbackBusinessById(id: number) {
  return fallbackBusinesses.find((business) => business.id === id) ?? null;
}

export function getFallbackBusinesses(params?: {
  search?: string;
  categoryId?: number;
  page?: number;
  limit?: number;
}): BusinessListResponse {
  const search = normalizeTerm(params?.search);
  const page = params?.page ?? 1;
  const limit = params?.limit ?? fallbackBusinesses.length;

  const filtered = fallbackBusinesses.filter((business) => {
    const matchesCategory = params?.categoryId
      ? business.categoryId === params.categoryId
      : true;

    if (!matchesCategory) {
      return false;
    }

    if (!search) {
      return true;
    }

    const haystack = normalizeTerm(
      [
        business.name,
        business.description,
        business.address,
        business.categoryName,
      ].join(" "),
    );

    return haystack.includes(search);
  });

  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / limit));
  const safePage = Math.min(Math.max(page, 1), totalPages);
  const start = (safePage - 1) * limit;

  return {
    businesses: filtered.slice(start, start + limit),
    total,
    page: safePage,
    totalPages,
  };
}
